services:
  postgres:
    image: postgres:16
    container_name: ifc-jornada-postgres
    environment:
      POSTGRES_DB: ifc_jornada
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ifc_jornada_pgdata:/var/lib/postgresql/data

volumes:
  ifc_jornada_pgdata: